export interface Admin {

    id: number,
    userName: string,
    password: string,
    firstName: string,
    lastName: string,
    email: string,
    phoneNumber: string,
    enabled: boolean,
    version: string,
    roleNames: string,
    listRoles: string[],
    listFavoris: string[],
    atelierId: number,
    clientId:number,
    familleTissuId: number,
    familleFournitureId: number,
    personnelId: number,
    favoris: string,
    roleId: number,
    role: string,
    atelier:string,
    client:string,
    familleFournitur: string,
    familleTissu: string,
    operationsNames: string,
    operationActive: boolean
}
